# Site
name: Ashok Koyi
description: Founder @ 1Ton Technologies
meta_description: Personnel blog of Ashok Koyi
logo: assets/images/me.jpeg
baseurl:
google_analytics: UA-126686252-1
mailchimp-list: https://eepurl.com/dIHLhL
github_comments_repository: thekalinga/thekalinga.github.io-comments
timezone: Asia/Kolkata
url: https://thekalinga.in
permalink: /:year/:month/:day/:title/

# Social
linkedin: https://linkedin.com/in/thekalinga
facebook: https://facebook.com/thekalinga
facebook_profile_username: thekalinga
facebook_profile_id: 100000738877942
twitter: https://twitter.com/thekalinga
twitter_username_with_prefix: '@thekalinga'
google: https://plus.google.com/111348232504336031712

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - year
    - month
    - day
  layout: archive
  permalinks:
    categories: '/categories/'
    tags: '/tags/'
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown
highlighter: rouge
# uncomment if you dont want future dated posts to appear
#future: true

#TODO Make sure you implement search in the header bar of the page
#https://blog.webjeda.com/instant-jekyll-search/
